stages:
  data_ingestion:
    cmd : python -m src.data_ingestion
    deps : 
      - src/data_ingestion.py
      - data/raw/personality_dataset.csv
    outs :
      - local_S3/data/raw/

  data_preprocessing:
    cmd : python -m src.data_preprocessing
    deps:
      - src/data_preprocessing.py
      - local_S3/data/raw/raw_data.csv
    params:
      - data_preprocessing.test_size
    outs:
      - local_S3/data/processed/train.csv
      - local_S3/data/processed/test.csv
      - local_S3/models/preprocessing_pipeline.pkl
      - local_S3/models/label_encoder.pkl
  
  model_training:
    cmd : python -m src.model_training
    deps:
      - src/model_training.py
      - local_S3/data/processed/train.csv
    params:
      - model_training.model_type
      - model_training.logistic_regression.C
      - model_training.logistic_regression.penalty
      - model_training.logistic_regression.solver
      - model_training.svc.C
      - model_training.svc.kernel
    outs:
      - local_S3/models/trained_model.pkl

  model_evaluation:
    cmd : python -m src.model_evaluation
    deps : 
      - src/model_evaluation.py
      - local_S3/models/trained_model.pkl
      - local_S3/data/processed/test.csv
    params :
      - model_training.model_type
    outs:
      - local_S3/metrics/metrics.json
      - local_S3/model_info/model_info.json
  
  model_registy:
    cmd: python -m src.model_registry
    deps :
      - src/model_registry.py
      - local_S3/model_info/model_info.json
