data_preprocessing:
  test_size : 0.15

model_training:
  model_type : logistic_regression
  logistic_regression:
    C: 0.01
    penalty: l1
    solver: liblinear

  svc:
    C: 0.01
    kernel : rbf